// Build: cc -O2 f128_constants.c -lmpfr -lgmp -o /tmp/f128-constants
// Run from oxide-go/runtime: /tmp/f128-constants > f128_constants.go
#include <assert.h>
#include <inttypes.h>
#include <mpfr.h>
#include <stdio.h>

static void wide(mpfr_t x) {
    uint64_t words[4] = {0};
    mpz_t n;
    mpz_init(n);
    mpfr_get_z_2exp(n, x);
    mpz_abs(n, n);
    mpz_clrbit(n, 236);
    size_t count;
    mpz_export(words, &count, -1, sizeof(uint64_t), 0, 0, n);
    words[3] |= (uint64_t)(mpfr_get_exp(x) - 1 + 262143) << 44;
    if (mpfr_signbit(x)) words[3] |= UINT64_C(1) << 63;
    printf("{0x%016"PRIx64",0x%016"PRIx64",0x%016"PRIx64",0x%016"PRIx64"}",words[3],words[2],words[1],words[0]);
    mpz_clear(n);
}

// Continued-fraction convergents give the best approximations of the second
// kind. Check every binary128 exponent, including every possible 113-bit
// significand via its denominator bound, rather than sampling significands.
// The true 2/pi lies between C/2^K and (C+1)/2^K. This certificate bounds the
// distance of x*2/pi from an integer from below by 2^-256. Consequently truncating
// the expansion cannot lose the sign/quadrant or the binary128 residual.
static void certify_reduction(const mpz_t c, unsigned k) {
    mpz_t r0,r1,r2,q0,q1,q2,a,bound,limit;
    mpz_inits(r0,r1,r2,q0,q1,q2,a,bound,limit,(mpz_ptr)0);
    mpz_set_ui(limit,1);mpz_mul_2exp(limit,limit,113);mpz_sub_ui(limit,limit,1);
    for (int e=-1;e<=16383;e++) {
        unsigned shift=k+112-e;
        mpz_fdiv_r_2exp(r0,c,shift);
        mpz_set_ui(r1,1);mpz_mul_2exp(r1,r1,shift);
        mpz_set_ui(q0,1);mpz_set_ui(q1,0);
        for (;;) {
            assert(mpz_sgn(r1)>0);
            mpz_fdiv_qr(a,r2,r0,r1);
            mpz_mul(q2,a,q1);mpz_add(q2,q2,q0);
            if (mpz_cmp(q2,limit)>0) break;
            mpz_swap(q0,q1);mpz_swap(q1,q2);
            mpz_swap(r0,r1);mpz_swap(r1,r2);
        }
        mpz_set_ui(bound,1);mpz_mul_2exp(bound,bound,shift-256);mpz_add(bound,bound,limit);
        assert(mpz_cmp(r1,bound)>0);
    }
    mpz_clears(r0,r1,r2,q0,q1,q2,a,bound,limit,(mpz_ptr)0);
}

int main(void) {
    enum { K = 16896 };
    mpfr_t lo, hi, x, temp;
    mpfr_inits2(K + 256, lo, hi, (mpfr_ptr)0);
    mpfr_init2(x, 237);
    mpfr_init2(temp, 512);
    mpfr_const_pi(lo, MPFR_RNDD);
    mpfr_const_pi(hi, MPFR_RNDU);
    mpfr_ui_div(lo, 2, lo, MPFR_RNDU);
    mpfr_ui_div(hi, 2, hi, MPFR_RNDD);
    mpfr_mul_2ui(lo, lo, K, MPFR_RNDU);
    mpfr_mul_2ui(hi, hi, K, MPFR_RNDD);
    mpz_t lower, upper;
    mpz_inits(lower, upper, (mpz_ptr)0);
    mpfr_get_z(lower, hi, MPFR_RNDD);
    mpfr_get_z(upper, lo, MPFR_RNDD);
    assert(mpz_cmp(lower, upper) == 0);
    certify_reduction(lower,K);
    uint64_t words[K/64] = {0};
    size_t count;
    mpz_export(words, &count, -1, sizeof(uint64_t), 0, 0, lower);
    printf("// Code generated by testdata/f128_constants.c with MPFR; DO NOT EDIT.\npackage oxide\n\nimport \"github.com/shogo82148/floats\"\n\n");
    printf("// floor(2/pi * 2^%d), least significant word first.\nconst f128ReductionBits = %d\nvar f128TwoOverPi = [...]uint64{\n", K, K);
    for (int i=0; i<K/64; i++) printf("0x%016"PRIx64",\n",words[i]);
    printf("}\n\nvar f128PiOver2 = floats.Float256");
    mpfr_const_pi(x, MPFR_RNDN);
    mpfr_div_2ui(x, x, 1, MPFR_RNDN);
    wide(x);
    printf("\nvar f128TwoOverSqrtPi = floats.Float256");
    mpfr_const_pi(temp, MPFR_RNDN);
    mpfr_sqrt(temp, temp, MPFR_RNDN);
    mpfr_ui_div(x, 2, temp, MPFR_RNDN);
    wide(x);
    printf("\nvar f128Ln2 = floats.Float256");
    mpfr_const_log2(x,MPFR_RNDN);wide(x);
    printf("\nvar f128Log2E = floats.Float256");
    mpfr_const_log2(temp,MPFR_RNDN);mpfr_ui_div(x,1,temp,MPFR_RNDN);wide(x);
    printf("\nvar f128Log10E = floats.Float256");
    mpfr_set_ui(temp,10,MPFR_RNDN);mpfr_log(temp,temp,MPFR_RNDN);mpfr_ui_div(x,1,temp,MPFR_RNDN);wide(x);
    printf("\nvar f128SqrtHalf = floats.Float256");
    mpfr_set_ui(x,2,MPFR_RNDN);mpfr_sqrt(x,x,MPFR_RNDN);mpfr_div_2ui(x,x,1,MPFR_RNDN);wide(x);
    printf("\nvar f128ExpCoefficients = [...]floats.Float256{\n");
    for (unsigned i=1;i<=40;i++) {
        mpfr_fac_ui(temp,i,MPFR_RNDN);mpfr_ui_div(x,1,temp,MPFR_RNDN);wide(x);printf(",\n");
    }
    printf("}\nvar f128LogCoefficients = [...]floats.Float256{\n");
    for (unsigned i=0;i<=40;i++) {
        mpfr_set_ui(temp,2*i+1,MPFR_RNDN);mpfr_ui_div(x,1,temp,MPFR_RNDN);wide(x);printf(",\n");
    }
    printf("}\n");
    printf("\nvar f128ErfCoefficients = [...]floats.Float256{\n");
    for (unsigned i=0;i<=80;i++) {
        mpfr_fac_ui(temp,i,MPFR_RNDN);mpfr_mul_ui(temp,temp,2*i+1,MPFR_RNDN);
        mpfr_ui_div(x,1,temp,MPFR_RNDN);
        if (i&1) mpfr_neg(x,x,MPFR_RNDN);
        wide(x);printf(",\n");
    }
    printf("}\n");
    for (int sine=0; sine<=1; sine++) {
        printf("\nvar f128%sCoefficients = [...]floats.Float256{\n", sine?"Sin":"Cos");
        for (unsigned i=0; i<=25; i++) {
            mpfr_fac_ui(temp, 2*i+sine, MPFR_RNDN);
            mpfr_ui_div(x, 1, temp, MPFR_RNDN);
            if (i&1) mpfr_neg(x,x,MPFR_RNDN);
            wide(x);printf(",\n");
        }
        printf("}\n");
    }
    mpfr_clears(lo,hi,x,temp,(mpfr_ptr)0);
    mpz_clears(lower,upper,(mpz_ptr)0);
    return 0;
}
