package mir

import (
	"bytes"
	"fmt"
	"go/build"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratedFiles(t *testing.T) {
	src := []byte(fmt.Sprintf(`//go:build linux && %s

// Code generated by oxide; DO NOT EDIT.
package fixture

import (
 "math"
 "unsafe"
 _ "embed"
 _ "math/big"
)

//go:embed payload.txt
var payload string

type Value struct { x float64 }

var value = Value{x: math.Sqrt(81)}

var width = unsafe.Sizeof(value)

var order int

func init() { order = order*10 + 1 }

func init() { order = order*10 + 2 }

func Result() (float64, uintptr, string, int) { return value.x, width, payload, order }
`, runtime.GOARCH))
	files, err := splitGeneratedFiles(src, 24, 320)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) < 3 {
		t.Fatalf("only %d files", len(files))
	}
	for i, f := range files {
		if f.name != fmt.Sprintf("oxide_gen_%05d.go", i) {
			t.Fatalf("filename: %s", f.name)
		}
		if !bytes.HasPrefix(f.data, []byte(fmt.Sprintf("//go:build linux && %s\n", runtime.GOARCH))) {
			t.Fatalf("lost build tag: %s", f.data)
		}
		if bytes.Contains(f.data, []byte(`_ "embed"`)) != bytes.Contains(f.data, []byte("//go:embed payload.txt\nvar payload")) {
			t.Fatalf("embed directive/import separated: %s", f.data)
		}
		if bytes.Contains(f.data, []byte(`_ "math/big"`)) != (i == 0) {
			t.Fatalf("blank import not in first file: %s", f.data)
		}
	}
	dir := t.TempDir()
	write := func(name, text string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(text), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module oxide-split-test\n\ngo 1.27.1\n")
	write("payload.txt", "embedded bytes")
	write("oxide_gen.go", "old single output")
	write("oxide_gen_99999.go", "old extra shard")
	write("oxide_gen_manual.go", "package fixture\n")
	write("oxide_gen_1.go", "package fixture\n")
	write("oxide_gen_test.go", `package fixture
import "testing"
func TestResult(t *testing.T) {
 value,width,payload,order:=Result()
 if value!=9 || width!=8 || payload!="embedded bytes" || order!=12 { t.Fatalf("result: %v %v %q %d",value,width,payload,order) }
}
`)
	paths, err := publishGeneratedFiles(dir, files)
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) != len(files) {
		t.Fatalf("published %d paths for %d files", len(paths), len(files))
	}
	for _, name := range []string{"oxide_gen.go", "oxide_gen_99999.go"} {
		if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
			t.Fatalf("stale %s: %v", name, err)
		}
	}
	for _, name := range []string{"oxide_gen_manual.go", "oxide_gen_1.go", "oxide_gen_test.go"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Fatalf("unmanaged %s: %v", name, err)
		}
	}
	for _, f := range files {
		for _, arch := range []string{"amd64", "arm64"} {
			ctx := build.Default
			ctx.GOOS, ctx.GOARCH = "linux", arch
			match, err := ctx.MatchFile(dir, f.name)
			if err != nil || match != (arch == runtime.GOARCH) {
				t.Fatalf("build tag %s/%s: %v %v", f.name, arch, match, err)
			}
		}
	}
	cmd := exec.Command("go", "test", "-count=1", ".")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOOS=linux", "GOARCH="+runtime.GOARCH, "GOWORK=off", "CGO_ENABLED=0")
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("compile split output: %v\n%s", err, output)
	}
	// A later, smaller translation removes all superseded numeric shards.
	if _, err := WriteGoFiles(dir, []byte("package fixture\nvar replacement = 1\n")); err != nil {
		t.Fatal(err)
	}
	for _, f := range files[1:] {
		if _, err := os.Stat(filepath.Join(dir, f.name)); !os.IsNotExist(err) {
			t.Fatalf("superseded %s: %v", f.name, err)
		}
	}
}

func TestGeneratedFileLimits(t *testing.T) {
	var src strings.Builder
	src.WriteString("// Code generated by oxide; DO NOT EDIT.\npackage fixture\n")
	for i := range 100 {
		fmt.Fprintf(&src, "var v%d = %q\n", i, strings.Repeat("x", 64))
	}
	for _, limits := range [][2]int{{20, 1 << 20}, {30_000, 512}} {
		files, err := splitGeneratedFiles([]byte(src.String()), limits[0], limits[1])
		if err != nil {
			t.Fatal(err)
		}
		if len(files) < 2 {
			t.Fatal("output was not split")
		}
		for _, f := range files {
			if n := bytes.Count(f.data, []byte{'\n'}); n > limits[0] || len(f.data) > limits[1] {
				t.Fatalf("%s exceeds limit: %d lines, %d bytes", f.name, n, len(f.data))
			}
		}
	}
}
