package mir

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/scanner"
	"go/token"
	"math/big"
	"sort"
	"strconv"
	"strings"
)

type generator struct {
	p                     *Program
	types                 map[int]*Type
	functions             map[string]*Function
	names                 map[string]string
	b                     strings.Builder
	f                     *Function
	frame                 map[int]uint64
	frameSize, frameAlign uint64
	tmp                   int
	allocs                map[uint64]Allocation
	knownAllocs           map[uint64]bool
	functionAllocs        map[uint64]string
	addressAllocs         map[uint64]uint64
	aliasAllocs           map[uint64]uint64
	externalAllocs        map[uint64]*External
	destructorTypes       map[int]bool
	consts                map[string]string
	arrays                map[[2]uint64]int
	extraTypes            []*Type
	nextType              int
	apiTypes              map[int]*Type
}
type generationError string

func Generate(p *Program, packageName string) (out []byte, err error) {
	var g *generator
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(generationError); ok {
				err = fmt.Errorf("%s", e)
			} else if e, ok := r.(error); ok {
				name := ""
				if g != nil && g.f != nil {
					name = g.f.Name + ": "
				}
				err = fmt.Errorf("%sMIR lowering: %w", name, e)
			} else {
				panic(r)
			}
		}
	}()
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf("invalid Go package %q", packageName)
	}
	if err := p.Validate(); err != nil {
		return nil, err
	}
	arch, err := p.GoArch()
	if err != nil {
		return nil, err
	}
	g, err = newGenerator(p)
	if err != nil {
		return nil, err
	}
	g.validatePublicDrops()
	required := map[string]bool{}
	if p.ProcessExitSymbol != "" {
		required[p.ProcessExitSymbol] = true
	}
	for _, r := range p.Roots {
		required[r.Symbol] = true
	}
	for _, d := range p.PublicDropTypes {
		required[d.Symbol] = true
	}
	for _, t := range p.APITypes {
		for _, symbol := range []string{t.DropSymbol, t.DefaultSymbol, t.DisplaySymbol} {
			if symbol != "" {
				required[symbol] = true
			}
		}
		if d := t.Debug; d != nil {
			required[d.ArgumentSymbol] = true
			required[d.ArgumentsSymbol] = true
			required[d.FormatSymbol] = true
		}
		for _, it := range []*IterationAPI{t.Iteration, t.MutableIteration} {
			if it != nil {
				required[it.Symbol] = true
				required[it.NextSymbol] = true
			}
		}
		if j := t.JSON; j != nil {
			if j.SerializeSymbol != "" {
				required[j.SerializeSymbol] = true
			}
			if j.DeserializeSymbol != "" {
				required[j.DeserializeSymbol] = true
			}
			if j.ValueSymbol != "" {
				required[j.ValueSymbol] = true
			}
		}
	}
	for _, f := range p.Functions {
		for _, call := range f.AssertCalls {
			required[call.Symbol] = true
		}
		for _, s := range f.Calls {
			if !strings.HasPrefix(s, "<") {
				required[s] = true
			}
		}
	}
	for _, t := range p.Types {
		if t.Function != "" {
			required[t.Function] = true
		}
	}
	for _, s := range g.functionAllocs {
		required[s] = true
	}
	g.line("//go:build linux && %s\n", arch)
	g.line("// Code generated by oxide from %s; DO NOT EDIT.", p.Compiler)
	g.line("// Target: %s", p.Target)
	g.line("package %s", packageName)
	imports := "\"unsafe\"; \"math\"; oxide \"github.com/csbxd/oxide/oxide-go/runtime\""
	if len(p.Allocations) > 0 {
		imports += "; _ \"embed\""
	}
	g.line("import (%s)", imports)
	if len(p.Allocations) > 0 {
		g.line("//go:embed oxide_alloc.bin\nvar oxideAllocImage []byte\nvar oxideGlobals *oxide.Globals")
		g.line("func init(){ oxideGlobals=oxide.LoadAllocations(oxideAllocImage, []oxide.AddressAllocation{")
		ids := make([]int, 0, len(g.functionAllocs))
		for id := range g.functionAllocs {
			ids = append(ids, int(id))
		}
		sort.Ints(ids)
		for _, id := range ids {
			symbol := g.functionAllocs[uint64(id)]
			name := g.names[symbol]
			if name == "" {
				g.fail("allocation %d has no translated function %s", id, symbol)
			}
			if g.functions[symbol].TrackCaller {
				g.fail("allocation %d references track_caller function %s without a function-pointer shim", id, symbol)
			}
			g.line("{%d,oxide.FunctionPointer(%s)},", id, name)
		}
		ids = ids[:0]
		for id := range g.addressAllocs {
			ids = append(ids, int(id))
		}
		sort.Ints(ids)
		for _, id := range ids {
			g.line("{%d,uintptr(%d)},", id, g.addressAllocs[uint64(id)])
		}
		ids = ids[:0]
		for id := range g.externalAllocs {
			ids = append(ids, int(id))
		}
		sort.Ints(ids)
		for _, id := range ids {
			address := fmt.Sprintf("oxide.FunctionPointer(oxideWeak%d)", id)
			if g.externalAllocs[uint64(id)].Symbol == "__dso_handle" {
				address = "oxide.DSOHandle()"
			}
			g.line("{%d,oxide.ConstAlloc([]byte{0,0,0,0,0,0,0,0},8,[]oxide.Relocation{{Offset:0,Target:%s}})},", id, address)
		}
		g.line("}, []oxide.AllocationAlias{")
		ids = ids[:0]
		for id := range g.aliasAllocs {
			ids = append(ids, int(id))
		}
		sort.Ints(ids)
		for _, id := range ids {
			g.line("{%d,%d},", id, g.aliasAllocs[uint64(id)])
		}
		g.line("}) }")
	}
	g.line("var _ unsafe.Pointer; var _ = math.Float32frombits; var oxideZero [0]uint64")
	g.externalFunctions()
	sort.Slice(p.Types, func(i, j int) bool { return p.Types[i].ID < p.Types[j].ID })
	for i := range p.Types {
		g.types[p.Types[i].ID] = &p.Types[i]
	}
	for _, t := range p.Types {
		g.typeDecl(&t)
	}
	for i := range p.Functions {
		if p.Functions[i].Body == nil && p.Functions[i].Kind == "Item" && !required[p.Functions[i].Symbol] {
			continue
		}
		g.function(&p.Functions[i])
	}
	g.emitPublicTypes()
	g.emitRoots()
	g.emitProcessExit()
	for _, t := range g.extraTypes {
		g.typeDecl(t)
	}
	g.destructorAdapters()
	g.emitConstants()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "oxide_gen.go", g.b.String(), parser.ParseComments)
	if err != nil {
		if errors, ok := err.(scanner.ErrorList); ok && len(errors) > 0 {
			at := errors[0].Pos.Offset
			source := g.b.String()
			lo := max(0, at-300)
			hi := min(len(source), at+300)
			return nil, fmt.Errorf("format generated MIR: %w; source near error: %q", err, source[lo:hi])
		}
		return nil, fmt.Errorf("format generated MIR: %w", err)
	}
	// Compile-time intrinsic assertions can eliminate the final edge to an
	// MIR block. Go rejects unused labels even in otherwise valid code.
	ast.Inspect(file, func(n ast.Node) bool {
		f, ok := n.(*ast.FuncDecl)
		if !ok || f.Body == nil {
			return true
		}
		used := map[string]bool{}
		ast.Inspect(f.Body, func(n ast.Node) bool {
			if b, ok := n.(*ast.BranchStmt); ok && b.Label != nil {
				used[b.Label.Name] = true
			}
			return true
		})
		for i, s := range f.Body.List {
			if label, ok := s.(*ast.LabeledStmt); ok && !used[label.Label.Name] {
				f.Body.List[i] = label.Stmt
			}
		}
		return false
	})
	var outbuf bytes.Buffer
	if err := format.Node(&outbuf, fset, file); err != nil {
		return nil, fmt.Errorf("format generated MIR: %w", err)
	}
	return outbuf.Bytes(), nil
}

func newGenerator(p *Program) (*generator, error) {
	allocs, err := p.MemoryAllocations()
	if err != nil {
		return nil, err
	}
	am := map[uint64]Allocation{}
	for _, a := range allocs {
		am[a.ID] = a
	}
	g := &generator{p: p, types: map[int]*Type{}, functions: map[string]*Function{}, names: map[string]string{}, allocs: am, consts: map[string]string{}}
	g.arrays = map[[2]uint64]int{}
	g.knownAllocs = map[uint64]bool{}
	g.functionAllocs = map[uint64]string{}
	g.addressAllocs = map[uint64]uint64{}
	g.aliasAllocs = map[uint64]uint64{}
	g.externalAllocs = map[uint64]*External{}
	g.destructorTypes = map[int]bool{}
	for _, raw := range p.Allocations {
		a := decode[struct {
			ID          uint64    `json:"id"`
			Function    string    `json:"function"`
			Address     *uint64   `json:"address"`
			Alias       *uint64   `json:"alias"`
			External    *External `json:"external"`
			Unsupported string    `json:"unsupported"`
		}](raw)
		g.knownAllocs[a.ID] = true
		if a.External != nil {
			g.externalAllocs[a.ID] = a.External
			continue
		}
		if a.Unsupported != "" {
			continue
		}
		if a.Function != "" {
			g.functionAllocs[a.ID] = a.Function
		}
		if a.Address != nil {
			g.addressAllocs[a.ID] = *a.Address
		}
		if a.Alias != nil {
			g.aliasAllocs[a.ID] = *a.Alias
		}
	}
	for i := range p.Types {
		g.types[p.Types[i].ID] = &p.Types[i]
		g.nextType = max(g.nextType, p.Types[i].ID+1)
		if t := &p.Types[i]; t.Kind == "array" {
			g.arrays[[2]uint64{uint64(t.Element), t.Length}] = t.ID
		}
	}
	sort.Slice(p.Functions, func(i, j int) bool { return p.Functions[i].Symbol < p.Functions[j].Symbol })
	for i := range p.Functions {
		f := &p.Functions[i]
		g.functions[f.Symbol] = f
		g.names[f.Symbol] = fmt.Sprintf("f%d", i)
	}
	return g, nil
}

func (g *generator) typeDecl(t *Type) {
	if !t.Sized || g.scalar(t) != "" {
		return
	}
	if t.ValueABI == "ScalarPair" {
		g.scalarPairDecl(t)
		return
	}
	align := min(t.Align, 8)
	marker := "byte"
	if align > 1 {
		marker = fmt.Sprintf("uint%d", align*8)
	}
	g.line("// T%d: %s (Rust size %d, align %d).", t.ID, t.Name, t.Size, t.Align)
	// Region-erased instances can use distinct rustc type IDs for the same
	// storage. Aliases keep their by-value Go call representations identical.
	g.line("type T%d = struct { _ [0]%s; Data [%d]byte }", t.ID, marker, t.Size)
	g.line("var _ [%d-int(unsafe.Sizeof(T%d{}))]byte; var _ [int(unsafe.Sizeof(T%d{}))-%d]byte", t.Size, t.ID, t.ID, t.Size)
}

// MIR Subslice projections have no explicit result type. Rust guarantees
// array stride and alignment, so derive the shorter array from its element's
// compiler layout instead of retaining the original array's size.
func (g *generator) arrayType(element int, length uint64) int {
	key := [2]uint64{uint64(element), length}
	if id, ok := g.arrays[key]; ok {
		return id
	}
	e := g.typ(element)
	t := &Type{ID: g.nextType, Name: fmt.Sprintf("[%s; %d]", e.Name, length), Kind: "array", Sized: true, Size: e.Size * length, Align: e.Align, Element: element, Length: length}
	g.nextType++
	g.types[t.ID] = t
	g.arrays[key] = t.ID
	g.extraTypes = append(g.extraTypes, t)
	return t.ID
}

func (g *generator) line(f string, args ...any) { fmt.Fprintf(&g.b, f, args...); g.b.WriteByte('\n') }
func (g *generator) fail(f string, args ...any) {
	name := ""
	if g.f != nil {
		name = g.f.Name + ": "
	}
	panic(generationError(name + fmt.Sprintf(f, args...)))
}
func (g *generator) typ(id int) *Type {
	t := g.types[id]
	if t == nil {
		g.fail("missing type %d", id)
	}
	if t.LayoutError != "" {
		g.fail("%s layout: %s", t.Name, t.LayoutError)
	}
	return t
}
func (g *generator) scalar(t *Type) string {
	switch t.Kind {
	case "bool":
		return "bool"
	case "char":
		return "uint32"
	case "usize":
		return "uintptr"
	case "isize":
		return "int64"
	case "pointer":
		if t.Size == 8 {
			return "uintptr"
		}
	case "fnptr":
		return "uintptr"
	case "i8", "i16", "i32", "i64":
		return "int" + t.Kind[1:]
	case "i128":
		return "oxide.I128"
	case "u8", "u16", "u32", "u64":
		return "uint" + t.Kind[1:]
	case "u128":
		return "oxide.U128"
	case "f32", "f64":
		return "float" + t.Kind[1:]
	}
	if t.ValueABI == "Scalar" {
		if t.ABIScalar == nil {
			g.fail("missing scalar ABI for %s", t.Name)
		}
		s, size := g.primitive(*t.ABIScalar)
		if size != t.Size {
			g.fail("scalar ABI size for %s", t.Name)
		}
		return s
	}
	return ""
}
func (g *generator) goType(id int) string {
	t := g.typ(id)
	if !t.Sized {
		g.fail("unsized value %s", t.Name)
	}
	if s := g.scalar(t); s != "" {
		return s
	}
	return fmt.Sprintf("T%d", id)
}
func (g *generator) signature(f *Function) ([]int, int) {
	if f.Body != nil {
		params := []int{}
		for i := 1; i <= f.Body.ArgCount; i++ {
			id := f.Body.Locals[i].Type
			if f.Body.SpreadArg != nil && i == *f.Body.SpreadArg {
				params = append(params, g.typ(id).FieldTypes...)
			} else {
				params = append(params, id)
			}
		}
		return params, f.Body.Locals[0].Type
	}
	if f.Signature != nil {
		return f.Signature.Params, f.Signature.Return
	}
	g.fail("no signature for %s", f.Name)
	return nil, 0
}
func alignUp(n, a uint64) uint64 { return (n + a - 1) &^ (a - 1) }

func (g *generator) function(f *Function) {
	g.f = f
	g.tmp = 0
	params, ret := g.signature(f)
	decls := []string{"ctx *oxide.Context"}
	if g.indirectValue(ret) {
		decls = append(decls, "result uintptr")
	}
	if f.Body != nil && f.Body.SpreadArg != nil {
		for i := 1; i <= f.Body.ArgCount; i++ {
			id := f.Body.Locals[i].Type
			if i == *f.Body.SpreadArg {
				for j, t := range g.typ(id).FieldTypes {
					decls = append(decls, fmt.Sprintf("spread%d %s", j, g.argumentType(t)))
				}
			} else {
				decls = append(decls, fmt.Sprintf("v%d %s", i, g.argumentType(id)))
			}
		}
	} else {
		for i, t := range params {
			decls = append(decls, fmt.Sprintf("v%d %s", i+1, g.argumentType(t)))
		}
	}
	if f.TrackCaller {
		decls = append(decls, "caller uintptr")
	}
	if f.Signature != nil && f.Signature.Variadic {
		decls = append(decls, "variadic ...uintptr")
	}
	g.line("// %s", f.Name)
	g.line("func %s(%s) %s {", g.names[f.Symbol], strings.Join(decls, ","), g.returnType(ret))
	if f.EmptyDrop {
		g.line("return %s", g.zero(ret))
		g.line("}")
		return
	}
	if g.processStartupFunction(f, params, ret) {
		return
	}
	if f.Body == nil {
		if g.runtimeFunction(f, params, ret) {
			return
		}
		if g.synthesizedConstructor(f, params, ret) {
			return
		}
		g.fail("external/intrinsic body requires lowering (%s)", f.Kind)
	}
	g.frame = map[int]uint64{}
	g.frameSize = 0
	g.frameAlign = 1
	addressed := map[int]bool{}
	var markAddress func(json.RawMessage)
	markAddress = func(raw json.RawMessage) {
		var m map[string]json.RawMessage
		if json.Unmarshal(raw, &m) == nil {
			for k, v := range m {
				if k == "Ref" || k == "AddressOf" {
					a := decode[[]json.RawMessage](v)
					p := decode[Place](a[len(a)-1])
					if len(p.Projection) == 0 {
						addressed[p.Local] = true
					} else {
						kind, _ := variant(p.Projection[0])
						if kind != "Deref" {
							addressed[p.Local] = true
						}
					}
				}
				markAddress(v)
			}
		} else {
			var a []json.RawMessage
			if json.Unmarshal(raw, &a) == nil {
				for _, v := range a {
					markAddress(v)
				}
			}
		}
	}
	for _, bb := range f.Body.Blocks {
		for _, s := range bb.Statements {
			markAddress(s.Kind)
		}
		k, v := variant(bb.Terminator.Kind)
		if k == "Drop" {
			d := decode[struct {
				Place Place `json:"place"`
			}](v)
			if len(d.Place.Projection) == 0 {
				addressed[d.Place.Local] = true
			} else {
				op, _ := variant(d.Place.Projection[0])
				if op != "Deref" {
					addressed[d.Place.Local] = true
				}
			}
		}
	}
	for i, l := range f.Body.Locals {
		t := g.typ(l.Type)
		if addressed[i] || t.Align > 8 || g.indirectValue(l.Type) {
			g.frameSize = alignUp(g.frameSize, t.Align)
			g.frame[i] = g.frameSize
			g.frameSize += max(t.Size, 1)
			g.frameAlign = max(g.frameAlign, t.Align)
		}
	}
	if g.frameSize > 0 {
		g.line("mark:=ctx.Mark(); defer ctx.Restore(mark); bp:=ctx.Alloc(%d,%d); _ = bp", g.frameSize, g.frameAlign)
	}
	for i, l := range f.Body.Locals {
		spread := f.Body.SpreadArg != nil && i == *f.Body.SpreadArg
		if _, ok := g.frame[i]; ok {
			if i > 0 && i <= f.Body.ArgCount && !spread {
				p := g.place(Place{Local: i})
				g.storeValue(p, fmt.Sprintf("v%d", i))
			}
			continue
		}
		if i > 0 && i <= f.Body.ArgCount && !spread {
			continue
		}
		g.line("var v%d %s; _ = v%d", i, g.goType(l.Type), i)
	}
	if f.Body.SpreadArg != nil {
		p := g.place(Place{Local: *f.Body.SpreadArg})
		t := g.typ(p.typ)
		if len(t.FieldTypes) != len(t.Fields) {
			g.fail("spread tuple layout")
		}
		for j, id := range t.FieldTypes {
			field := g.storageLocation(fmt.Sprintf("unsafe.Add(%s,%d)", p.address, t.Fields[j]), id)
			g.storeValue(field, fmt.Sprintf("spread%d", j))
		}
	}
	g.line("var unwind any; _ = unwind; goto bb0")
	for i, bb := range f.Body.Blocks {
		g.line("bb%d:;", i)
		for _, s := range bb.Statements {
			g.statement(s.Kind)
		}
		g.terminator(i, bb.Terminator.Kind, ret)
	}
	g.line("}")
}

func (g *generator) synthesizedConstructor(f *Function, params []int, ret int) bool {
	if f.Kind != "Item" || f.Constructor == nil {
		return false
	}
	r := g.typ(ret)
	idx := *f.Constructor
	if r.Kind != "aggregate" || idx < 0 || idx >= len(r.VariantFieldTypes) {
		return false
	}
	fields := r.VariantFieldTypes[idx]
	if len(fields) != len(params) {
		return false
	}
	offsets := r.Fields
	if idx < len(r.Variants) && len(r.Variants[idx]) == len(fields) {
		offsets = r.Variants[idx]
	}
	if len(offsets) != len(fields) {
		return false
	}
	address := "unsafe.Pointer(&r)"
	if g.indirectValue(ret) {
		g.line("{ mark:=ctx.Mark(); defer ctx.Restore(mark); r:=ctx.Alloc(%d,%d)", r.Size, r.Align)
		address = "unsafe.Pointer(r)"
	} else {
		g.line("{ var r %s", g.goType(ret))
	}
	for i, ft := range fields {
		if ft != params[i] {
			g.fail("constructor field type %d", i)
		}
		if g.indirectValue(ft) {
			g.copyValue(fmt.Sprintf("unsafe.Add(%s,%d)", address, offsets[i]), fmt.Sprintf("unsafe.Pointer(v%d)", i+1), g.typ(ft).Size)
		} else if g.scalar(g.typ(ft)) != "" {
			g.line("*(*%s)(unsafe.Add(%s,%d))=v%d", g.goType(ft), address, offsets[i], i+1)
		} else {
			g.line("copy(unsafe.Slice((*byte)(unsafe.Add(%s,%d)),%d),unsafe.Slice((*byte)(unsafe.Pointer(&v%d)),%d))", address, offsets[i], g.typ(ft).Size, i+1, g.typ(ft).Size)
		}
	}
	g.setTag(location{g: g, address: address, typ: ret}, idx)
	if g.indirectValue(ret) {
		g.copyValue("unsafe.Pointer(result)", address, r.Size)
		g.line("return }")
	} else {
		g.line("return r }")
	}
	g.line("}")
	return true
}
func (g *generator) zero(id int) string {
	t := g.typ(id)
	if g.scalar(t) == "oxide.I128" || g.scalar(t) == "oxide.U128" {
		return g.goType(id) + "{}"
	}
	if t.Kind == "bool" {
		return "false"
	}
	if g.scalar(t) != "" {
		return "0"
	}
	return g.goType(id) + "{}"
}

type location struct {
	g       *generator
	address string
	typ     int
	meta    string
	variant int
	local   string
}

func (p location) read() string {
	if p.g.indirectValue(p.typ) {
		p.g.fail("large value %s requires storage access", p.g.typ(p.typ).Name)
	}
	if t := p.g.typ(p.typ); t.Sized && t.Size == 0 {
		// A Rust ZST may reside at a dangling non-null address, such as 1.
		// Go can nil-check even a zero-byte load/store at that address. Its
		// value has no bytes, so use addressable static storage for reads and
		// writes. Address-of projections still retain the Rust pointer.
		return fmt.Sprintf("*(*%s)(unsafe.Pointer(&oxideZero))", p.g.goType(p.typ))
	}
	if p.local != "" {
		return p.local
	}
	return fmt.Sprintf("*(*%s)(%s)", p.g.goType(p.typ), p.address)
}
func (g *generator) place(p Place) location {
	if p.Local >= len(g.f.Body.Locals) {
		g.fail("invalid local %d", p.Local)
	}
	t := g.f.Body.Locals[p.Local].Type
	r := location{g: g, typ: t, local: fmt.Sprintf("v%d", p.Local), variant: -1}
	if off, ok := g.frame[p.Local]; ok {
		r.local = ""
		r.address = fmt.Sprintf("unsafe.Pointer(bp+%d)", off)
	} else {
		r.address = fmt.Sprintf("unsafe.Pointer(&v%d)", p.Local)
	}
	for _, raw := range p.Projection {
		kind, a := variant(raw)
		ty := g.typ(r.typ)
		switch kind {
		case "Deref":
			if ty.Kind != "pointer" {
				g.fail("deref nonpointer %s", ty.Name)
			}
			r.meta = ""
			if ty.Size > 8 {
				r.meta = fmt.Sprintf("*(*uintptr)(unsafe.Add(%s,8))", r.address)
				r.address = fmt.Sprintf("unsafe.Pointer(*(*uintptr)(%s))", r.address)
			} else {
				r.address = "unsafe.Pointer(" + r.read() + ")"
			}
			r.typ = ty.Pointee
			r.local = ""
			r.variant = -1
		case "Field":
			pair := decode[[]int](a)
			offsets := ty.Fields
			if ty.Size == 0 && len(offsets) == 0 {
				r.typ = pair[1]
				r.local = ""
				continue
			}
			if r.variant >= 0 && len(ty.Variants) > 0 {
				offsets = ty.Variants[r.variant]
			}
			if pair[0] >= len(offsets) {
				g.fail("missing field %d in %s", pair[0], ty.Name)
			}
			offset := fmt.Sprint(offsets[pair[0]])
			field := g.typ(pair[1])
			if !field.Sized && offsets[pair[0]] != 0 {
				if r.meta == "" {
					g.fail("unsized field without metadata in %s", ty.Name)
				}
				_, align, ok := g.dstSizeAlign(field, r.meta)
				if !ok {
					g.fail("unsupported unsized field in %s", ty.Name)
				}
				offset = dstAlignUp(offset, dstFieldAlign(ty, align))
			}
			r.address = fmt.Sprintf("unsafe.Add(%s,%s)", r.address, offset)
			r.typ = pair[1]
			if g.typ(r.typ).Sized {
				r.meta = ""
			}
			r.local = ""
			r.variant = -1
		case "Downcast":
			r.variant = decode[int](a)
		case "OpaqueCast":
			r.typ = decode[int](a)
			r.local = ""
		case "Index":
			idx := g.place(Place{Local: decode[int](a)}).read()
			stride := g.typ(ty.Element).Size
			r.address = fmt.Sprintf("unsafe.Add(%s,uintptr(%s)*%d)", r.address, idx, stride)
			r.typ = ty.Element
			r.meta = ""
			r.local = ""
		case "ConstantIndex":
			x := decode[struct {
				Offset  uint64 `json:"offset"`
				FromEnd bool   `json:"from_end"`
			}](a)
			index := fmt.Sprint(x.Offset)
			if x.FromEnd {
				index = fmt.Sprintf("(%s-%d)", g.length(r), x.Offset)
			}
			r.address = fmt.Sprintf("unsafe.Add(%s,uintptr(%s)*%d)", r.address, index, g.typ(ty.Element).Size)
			r.typ = ty.Element
			r.meta = ""
			r.local = ""
		case "Subslice":
			x := decode[struct {
				From    uint64 `json:"from"`
				To      uint64 `json:"to"`
				FromEnd bool   `json:"from_end"`
			}](a)
			if ty.Kind != "slice" && ty.Kind != "str" && ty.Kind != "array" {
				g.fail("subslice of %s", ty.Name)
			}
			elemSize := uint64(1)
			if ty.Kind != "str" {
				elemSize = g.typ(ty.Element).Size
			}
			start := x.From
			var length string
			if ty.Kind == "array" {
				end := x.To
				if x.FromEnd {
					end = ty.Length - x.To
				}
				if end < start {
					g.fail("invalid array subslice")
				}
				length = strconv.FormatUint(end-start, 10)
				r.typ = g.arrayType(ty.Element, end-start)
			} else {
				if r.meta == "" {
					g.fail("subslice without dynamic length")
				}
				if x.FromEnd {
					length = fmt.Sprintf("(%s-%d-%d)", r.meta, x.From, x.To)
				} else {
					length = strconv.FormatUint(x.To-x.From, 10)
				}
			}
			r.address = fmt.Sprintf("unsafe.Add(%s,%d*%d)", r.address, start, elemSize)
			r.meta = length
			r.local = ""
		default:
			g.fail("projection %s", kind)
		}
	}
	return r
}
func (g *generator) length(p location) string {
	t := g.typ(p.typ)
	if p.meta != "" {
		return p.meta
	}
	if t.Kind == "array" {
		return fmt.Sprintf("uintptr(%d)", t.Length)
	}
	g.fail("length without metadata: %s", t.Name)
	return ""
}

func (g *generator) operand(raw json.RawMessage) (string, int) {
	k, v := variant(raw)
	switch k {
	case "Copy", "Move":
		p := g.place(decode[Place](v))
		return p.value(), p.typ
	case "RuntimeChecks":
		name := decode[string](v)
		enabled, ok := g.p.RuntimeChecks[name]
		if !ok {
			g.fail("missing compiler runtime check configuration %s", name)
		}
		boolID := 0
		for id, t := range g.types {
			if t.Kind == "bool" {
				boolID = id
				break
			}
		}
		return strconv.FormatBool(enabled), boolID
	case "Constant":
		c := decode[struct {
			Const struct {
				Type int             `json:"ty"`
				Kind json.RawMessage `json:"kind"`
			} `json:"const_"`
		}](v)
		t := g.typ(c.Const.Type)
		kind, data := variant(c.Const.Kind)
		if kind == "ZeroSized" {
			return g.zero(t.ID), t.ID
		}
		if kind == "Ty" {
			q := decode[struct {
				Kind json.RawMessage `json:"kind"`
			}](data)
			kk, vv := variant(q.Kind)
			if kk != "Value" {
				g.fail("type constant %s", kk)
			}
			arr := decode[[]json.RawMessage](vv)
			data = arr[1]
		} else if kind != "Allocated" {
			g.fail("constant %s", kind)
		}
		a := decode[struct {
			Bytes      []*uint8 `json:"bytes"`
			Provenance struct {
				Ptrs []json.RawMessage `json:"ptrs"`
			} `json:"provenance"`
		}](data)
		if len(a.Provenance.Ptrs) > 0 || g.indirectValue(t.ID) {
			key := string(data)
			name, ok := g.consts[key]
			if !ok {
				name = fmt.Sprintf("constant%d", len(g.consts))
				g.consts[key] = name
			}
			if g.indirectValue(t.ID) {
				return name, t.ID
			}
			return fmt.Sprintf("*(*%s)(unsafe.Pointer(%s))", g.goType(t.ID), name), t.ID
		}
		bytes := make([]byte, len(a.Bytes))
		for i, p := range a.Bytes {
			if p != nil {
				bytes[i] = *p
			}
		}
		if g.scalar(t) == "" {
			if t.ValueABI == "ScalarPair" {
				return g.scalarPairConstant(t, bytes), t.ID
			}
			parts := []string{}
			for i, b := range bytes {
				if b != 0 {
					parts = append(parts, fmt.Sprintf("%d:%d", i, b))
				}
			}
			return fmt.Sprintf("T%d{Data:[%d]byte{%s}}", t.ID, t.Size, strings.Join(parts, ",")), t.ID
		}
		bits := new(big.Int)
		for i := len(bytes) - 1; i >= 0; i-- {
			bits.Lsh(bits, 8)
			bits.Or(bits, big.NewInt(int64(bytes[i])))
		}
		if t.Kind == "bool" {
			return strconv.FormatBool(bits.Sign() != 0), t.ID
		}
		if g.scalar(t) == "float32" {
			return "math.Float32frombits(" + bits.String() + ")", t.ID
		}
		if g.scalar(t) == "float64" {
			return "math.Float64frombits(" + bits.String() + ")", t.ID
		}
		if g.scalar(t) == "oxide.U128" || g.scalar(t) == "oxide.I128" {
			mask := new(big.Int).Lsh(big.NewInt(1), 64)
			lo := new(big.Int).Mod(new(big.Int).Set(bits), mask)
			hi := new(big.Int).Rsh(new(big.Int).Set(bits), 64)
			return fmt.Sprintf("%s{Lo:%s,Hi:%s}", g.goType(t.ID), lo.String(), hi.String()), t.ID
		}
		if strings.HasPrefix(g.scalar(t), "int") && len(bytes) > 0 && bytes[len(bytes)-1]&128 != 0 {
			bits.Sub(bits, new(big.Int).Lsh(big.NewInt(1), uint(8*len(bytes))))
		}
		return fmt.Sprintf("oxide.Scalar[%s](%s)", g.goType(t.ID), bits.String()), t.ID
	}
	g.fail("operand %s", k)
	return "", 0
}

func (g *generator) emitConstants() {
	keys := make([]string, 0, len(g.consts))
	for key := range g.consts {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool { return g.consts[keys[i]] < g.consts[keys[j]] })
	for _, key := range keys {
		g.emitConstant(g.consts[key], []byte(key))
	}
	ids := make([]uint64, 0, len(g.p.ThreadLocals))
	for id := range g.p.ThreadLocals {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	for _, id := range ids {
		var meta struct {
			External string `json:"external"`
		}
		if json.Unmarshal(g.p.ThreadLocals[id], &meta) == nil && meta.External != "" {
			continue
		}
		g.emitConstant(fmt.Sprintf("threadLocal%d", id), g.p.ThreadLocals[id])
	}
}
func (g *generator) emitConstant(name string, data []byte) {
	var a struct {
		Bytes      []*uint8 `json:"bytes"`
		Align      uint64   `json:"align"`
		Provenance struct {
			Ptrs [][]uint64 `json:"ptrs"`
		} `json:"provenance"`
	}
	if err := json.Unmarshal(data, &a); err != nil {
		g.fail("constant %v", err)
	}
	bytes := make([]string, len(a.Bytes))
	for i, b := range a.Bytes {
		bytes[i] = "0"
		if b != nil {
			bytes[i] = strconv.Itoa(int(*b))
		}
	}
	relocs := []string{}
	for _, p := range a.Provenance.Ptrs {
		if len(p) != 2 {
			g.fail("invalid relocation")
		}
		if !g.knownAllocs[p[1]] {
			g.fail("relocation to function/vtable/static allocation %d", p[1])
		}
		relocs = append(relocs, fmt.Sprintf("{%d,oxideGlobals.Get(%d)}", p[0], p[1]))
	}
	g.line("var %s uintptr; func init(){ %s=oxide.ConstAlloc([]byte{%s},%d,[]oxide.Relocation{%s}) }", name, name, strings.Join(bytes, ","), a.Align, strings.Join(relocs, ","))
}
